// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MultiTilemap","status":true,"description":"複数タイルマップイベント作成プラグイン","parameters":{"RegionColor":"#FF000080"}},
{"name":"NRP_ChangeCharacterSpeed","status":true,"description":"v1.01 キャラクターの移動速度を細かく変更します。","parameters":{"DefaultAlwaysDash":"","PlayerSpeed":"","PlusSpeedDash":"","<BasicSpeedRate>":"","PlayerBasicSpeedRate":"200","EventBasicSpeedRate":"100","<Vehicles>":"","BoatSpeed":"","ShipSpeed":"","AirShipSpeed":""}},
{"name":"WindowBackImage","status":true,"description":"ウィンドウ背景画像指定プラグイン","parameters":{"windowImageInfo":"[\"{\\\"WindowClass\\\":\\\"Window_Message\\\",\\\"ImageFile\\\":\\\"karidekaita\\\",\\\"WindowSkin\\\":\\\"\\\",\\\"OffsetX\\\":\\\"0\\\",\\\"OffsetY\\\":\\\"0\\\",\\\"ScaleX\\\":\\\"100\\\",\\\"ScaleY\\\":\\\"100\\\",\\\"WindowShow\\\":\\\"false\\\",\\\"SwitchId\\\":\\\"10\\\"}\"]"}},
{"name":"PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"WindowSkinSwitcher","status":true,"description":"ウィンドウスキン切り替えプラグイン","parameters":{"SkinInfoList":"[\"{\\\"SkinID\\\":\\\"1\\\",\\\"SkinFileName\\\":\\\"Window01\\\",\\\"BackOpacity\\\":\\\"192\\\"}\"]"}},
{"name":"AltMenuScreen2MZ","status":true,"description":"[Ver1.5.0]レイアウトの異なるメニュー画面","parameters":{"allowWindowDisp":"true","maxColsMenu":"4","commandRows":"2","commandCols":"4","isDisplayStatus":"true","doesDisplayNextLevel":"false","textNextLevel":"Next%1","statusStyle":"standard","display map name":"true","location string":"現在地:","bgBitmapMenu":"","doesNotSetItemScene":"true","bgBitmapItem":"","doesNotSetSkillScene":"true","bgBitmapSkill":"","doesNotSetEquipScene":"true","bgBitmapEquip":"","doesNotSetStatusScene":"true","bgBitmapStatus":"","doesNotSetOptionScene":"true","bgBitmapOptions":"","doesNotSetSaveScene":"true","bgBitmapFile":"","doesNotSetEndScene":"true","bgBitmapGameEnd":"","doesNotSetShopScene":"false","bgBitmapShop":"","doesNotSetNameScene":"true","bgBitmapNameInput":"","bgUserDefined":""}}
];
