// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MultiTilemap","status":true,"description":"複数タイルマップイベント作成プラグイン","parameters":{}},
{"name":"NRP_ChangeCharacterSpeed","status":true,"description":"v1.01 キャラクターの移動速度を細かく変更します。","parameters":{"DefaultAlwaysDash":"","PlayerSpeed":"","PlusSpeedDash":"","<BasicSpeedRate>":"","PlayerBasicSpeedRate":"200","EventBasicSpeedRate":"100","<Vehicles>":"","BoatSpeed":"","ShipSpeed":"","AirShipSpeed":""}},
{"name":"WindowBackImage","status":true,"description":"ウィンドウ背景画像指定プラグイン","parameters":{"windowImageInfo":""}}
];
